/**
 * E-Commerce Application
 *
 * Contact: sad@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CategoryDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminCategoriesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param categoryDTO 
     */
    createCategory(categoryDTO: CategoryDTO, extraHttpRequestParams?: any): Observable<CategoryDTO>;

    /**
     * 
     * 
     * @param id 
     */
    deleteCategory(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    getCategories(extraHttpRequestParams?: any): Observable<Array<CategoryDTO>>;

    /**
     * 
     * 
     * @param id 
     */
    getCategoryById1(id: number, extraHttpRequestParams?: any): Observable<CategoryDTO>;

    /**
     * 
     * 
     * @param categoryDTO 
     */
    updateCategory(categoryDTO: CategoryDTO, extraHttpRequestParams?: any): Observable<CategoryDTO>;

}
