/**
 * E-Commerce Application
 *
 * Contact: sad@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PagedResponseUserDTO } from '../model/models';
import { UserDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AdminUsersServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param pageNum 
     * @param pageSize 
     * @param sortField Field to sort by. Allowed values: BD, role, phone, creditLimit, userName, job, userId, email
     * @param sortDir Sort direction
     * @param keyword Keyword to search across multiple fields
     * @param userId Filter by user ID
     * @param userName Filter by username
     * @param email Filter by email
     * @param role Filter by user role
     * @param job Filter by job
     * @param phone Filter by phone number
     * @param creditLimitMin Filter by credit minim limit
     * @param creditLimitMax Filter by credit maximum limit
     */
    getAllUsers(pageNum?: number, pageSize?: number, sortField?: 'BD' | 'role' | 'phone' | 'creditLimit' | 'userName' | 'job' | 'userId' | 'email', sortDir?: 'asc' | 'desc', keyword?: any, userId?: any, userName?: any, email?: any, role?: 'USER' | 'ADMIN', job?: any, phone?: any, creditLimitMin?: any, creditLimitMax?: any, extraHttpRequestParams?: any): Observable<PagedResponseUserDTO>;

    /**
     * 
     * 
     * @param id 
     */
    getUserById(id: number, extraHttpRequestParams?: any): Observable<UserDTO>;

}
