export * from './admin-categories.service';
import { AdminCategoriesService } from './admin-categories.service';
export * from './admin-categories.serviceInterface';
export * from './admin-orders.service';
import { AdminOrdersService } from './admin-orders.service';
export * from './admin-orders.serviceInterface';
export * from './admin-products.service';
import { AdminProductsService } from './admin-products.service';
export * from './admin-products.serviceInterface';
export * from './admin-users.service';
import { AdminUsersService } from './admin-users.service';
export * from './admin-users.serviceInterface';
export * from './authentication.service';
import { AuthenticationService } from './authentication.service';
export * from './authentication.serviceInterface';
export * from './customer-addresses.service';
import { CustomerAddressesService } from './customer-addresses.service';
export * from './customer-addresses.serviceInterface';
export * from './customer-cart.service';
import { CustomerCartService } from './customer-cart.service';
export * from './customer-cart.serviceInterface';
export * from './customer-categories.service';
import { CustomerCategoriesService } from './customer-categories.service';
export * from './customer-categories.serviceInterface';
export * from './customer-orders.service';
import { CustomerOrdersService } from './customer-orders.service';
export * from './customer-orders.serviceInterface';
export * from './customer-products.service';
import { CustomerProductsService } from './customer-products.service';
export * from './customer-products.serviceInterface';
export * from './customer-profile.service';
import { CustomerProfileService } from './customer-profile.service';
export * from './customer-profile.serviceInterface';
export * from './customer-wishlist.service';
import { CustomerWishlistService } from './customer-wishlist.service';
export * from './customer-wishlist.serviceInterface';
export * from './user-controller2.service';
import { UserController2Service } from './user-controller2.service';
export * from './user-controller2.serviceInterface';
export const APIS = [AdminCategoriesService, AdminOrdersService, AdminProductsService, AdminUsersService, AuthenticationService, CustomerAddressesService, CustomerCartService, CustomerCategoriesService, CustomerOrdersService, CustomerProductsService, CustomerProfileService, CustomerWishlistService, UserController2Service];
