/**
 * E-Commerce Application
 *
 * Contact: sad@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { Token } from '../model/models';
import { UserSignInDTO } from '../model/models';
import { UserSignUpDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface AuthenticationServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param userSignInDTO 
     */
    login(userSignInDTO: UserSignInDTO, extraHttpRequestParams?: any): Observable<Token>;

    /**
     * 
     * 
     */
    logout(extraHttpRequestParams?: any): Observable<string>;

    /**
     * 
     * 
     * @param userSignUpDTO 
     */
    register(userSignUpDTO: UserSignUpDTO, extraHttpRequestParams?: any): Observable<Token>;

    /**
     * 
     * 
     */
    token(extraHttpRequestParams?: any): Observable<Token>;

}
