/**
 * E-Commerce Application
 *
 * Contact: sad@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { PagedResponseProductDTO } from '../model/models';
import { ProductDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CustomerProductsServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param id 
     */
    getProductById1(id: number, extraHttpRequestParams?: any): Observable<ProductDTO>;

    /**
     * 
     * 
     * @param name 
     */
    getProductByName(name: string, extraHttpRequestParams?: any): Observable<Array<ProductDTO>>;

    /**
     * 
     * 
     * @param quantity 
     */
    getProductByQuantity(quantity: number, extraHttpRequestParams?: any): Observable<Array<ProductDTO>>;

    /**
     * 
     * 
     * @param id 
     */
    getProductImages(id: number, extraHttpRequestParams?: any): Observable<Array<string>>;

    /**
     * 
     * 
     * @param pageNum 
     * @param pageSize 
     * @param sortField Field to sort by. Allowed values: quantity, productId, purchaseCount, price, description, categories, productName
     * @param sortDir Sort direction
     * @param keyword Keyword to search across multiple fields
     * @param productName Filter by product name
     * @param description Filter by description
     * @param priceMin Filter by minimum price
     * @param priceMax Filter by maximum price
     * @param quantityMin Filter by minimum quantity
     * @param quantityMax Filter by maximum quantity
     * @param categoryId Filter by categoryId
     * @param categoryName Filter by categoryName
     */
    getProducts1(pageNum?: number, pageSize?: number, sortField?: 'quantity' | 'productId' | 'purchaseCount' | 'price' | 'description' | 'categories' | 'productName', sortDir?: 'asc' | 'desc', keyword?: any, productName?: any, description?: any, priceMin?: any, priceMax?: any, quantityMin?: any, quantityMax?: any, categoryId?: any, categoryName?: any, extraHttpRequestParams?: any): Observable<PagedResponseProductDTO>;

}
