/**
 * E-Commerce Application
 *
 * Contact: sad@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AddressDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CustomerAddressesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param addressDTO 
     */
    createAddress(addressDTO: AddressDTO, extraHttpRequestParams?: any): Observable<AddressDTO>;

    /**
     * 
     * 
     * @param id 
     */
    deleteAddress(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     */
    getAllAddresses(extraHttpRequestParams?: any): Observable<Array<AddressDTO>>;

    /**
     * 
     * 
     * @param addressDTO 
     */
    updateAddress(addressDTO: AddressDTO, extraHttpRequestParams?: any): Observable<AddressDTO>;

}
