/**
 * E-Commerce Application
 *
 * Contact: sad@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CartDTO } from '../model/models';
import { PagedResponseCartDTO } from '../model/models';
import { ShoppingCartDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CustomerCartServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param shoppingCartDTO 
     */
    addOrUpdateCartItem(shoppingCartDTO: ShoppingCartDTO, extraHttpRequestParams?: any): Observable<CartDTO>;

    /**
     * 
     * 
     * @param productId 
     */
    getCartItem(productId: number, extraHttpRequestParams?: any): Observable<CartDTO>;

    /**
     * 
     * 
     * @param pageNum 
     * @param pageSize 
     * @param sortField Field to sort by. Allowed values: quantity, productId, userId
     * @param sortDir Sort direction
     * @param keyword Keyword to search across multiple fields
     * @param productName Filter by product name
     * @param description Filter by description
     * @param priceMin Filter by minimum price
     * @param priceMax Filter by maximum price
     * @param quantityMin Filter by minimum quantity
     * @param quantityMax Filter by maximum quantity
     * @param categoryId Filter by categoryId
     * @param categoryName Filter by categoryName
     */
    getCartItems(pageNum?: number, pageSize?: number, sortField?: 'quantity' | 'productId' | 'userId', sortDir?: 'asc' | 'desc', keyword?: any, productName?: any, description?: any, priceMin?: any, priceMax?: any, quantityMin?: any, quantityMax?: any, categoryId?: any, categoryName?: any, extraHttpRequestParams?: any): Observable<PagedResponseCartDTO>;

    /**
     * 
     * 
     * @param productId 
     */
    getProductTotalPrice(productId: number, extraHttpRequestParams?: any): Observable<number>;

    /**
     * 
     * 
     */
    getTotalPrice(extraHttpRequestParams?: any): Observable<number>;

    /**
     * 
     * 
     */
    getTotalQuantity(extraHttpRequestParams?: any): Observable<number>;

    /**
     * 
     * 
     * @param productId 
     */
    removeCartItem(productId: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param shoppingCartDTO 
     */
    removeOrUpdateCartItem(shoppingCartDTO: ShoppingCartDTO, extraHttpRequestParams?: any): Observable<CartDTO>;

}
