/**
 * E-Commerce Application
 *
 * Contact: sad@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CategoryDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CustomerCategoriesServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    getCategories1(extraHttpRequestParams?: any): Observable<Array<CategoryDTO>>;

    /**
     * 
     * 
     * @param id 
     */
    getCategoryById(id: number, extraHttpRequestParams?: any): Observable<CategoryDTO>;

}
