/**
 * E-Commerce Application
 *
 * Contact: sad@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ChangePasswordDTO } from '../model/models';
import { UpdateProfileDTO } from '../model/models';
import { UserDTO } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface CustomerProfileServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     */
    profile(extraHttpRequestParams?: any): Observable<UserDTO>;

    /**
     * 
     * 
     * @param changePasswordDTO 
     */
    updatePassword(changePasswordDTO: ChangePasswordDTO, extraHttpRequestParams?: any): Observable<{}>;

    /**
     * 
     * 
     * @param updateProfileDTO 
     */
    updateProfile(updateProfileDTO: UpdateProfileDTO, extraHttpRequestParams?: any): Observable<UserDTO>;

}
