/**
 * E-Commerce Application
 *
 * Contact: sad@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CustomerOrderStatsProjection { 
    email?: string;
    userId?: number;
    totalOrders?: number;
    averageOrderValue?: number;
    totalSpent?: number;
    lastOrderDate?: string;
    userName?: string;
}

