/**
 * E-Commerce Application
 *
 * Contact: sad@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DashboardSummaryProjection { 
    todayOrders?: number;
    todayRevenue?: number;
    totalUsers?: number;
    totalOrders?: number;
    pendingOrders?: number;
    totalRevenue?: number;
    newCustomersThisMonth?: number;
    revenueGrowthRate?: number;
}

