/**
 * E-Commerce Application
 *
 * Contact: sad@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderDetailsDTO } from './order-details-dto';


export interface OrderDTO { 
    orderId?: number;
    address?: string;
    price?: number;
    date?: string;
    status?: OrderDTO.StatusEnum;
    payType?: OrderDTO.PayTypeEnum;
    orderDetails?: Array<OrderDetailsDTO>;
    userId?: number;
}
export namespace OrderDTO {
    export const StatusEnum = {
        Processing: 'PROCESSING',
        Shipped: 'SHIPPED',
        Completed: 'COMPLETED',
        Canceled: 'CANCELED'
    } as const;
    export type StatusEnum = typeof StatusEnum[keyof typeof StatusEnum];
    export const PayTypeEnum = {
        Cash: 'CASH',
        Credit: 'CREDIT'
    } as const;
    export type PayTypeEnum = typeof PayTypeEnum[keyof typeof PayTypeEnum];
}


