/**
 * E-Commerce Application
 *
 * Contact: sad@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ProductSalesStatsProjection { 
    totalQuantity?: number;
    productId?: number;
    productName?: string;
    totalRevenue?: number;
    averageOrderQuantity?: number;
    orderCount?: number;
}

