/**
 * E-Commerce Application
 *
 * Contact: sad@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryNoProductDTO } from './category-no-product-dto';


export interface ProductDTO {
    productId?: number;
    productName: string;
    description: string;
    quantity?: number;
    price?: number;
    categories?: Array<CategoryNoProductDTO>;
    images?: Array<string>;
    purchaseCount?: number;
}

